apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager
spec:
  dnsNames:
    - hej.client.aldowntown.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
