# permissions for end users to view providers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-viewer-role
rules:
- apiGroups:
  - hostan.hostan.app
  resources:
  - providers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hostan.hostan.app
  resources:
  - providers/status
  verbs:
  - get
