apiVersion: app.hostan.app/v1
kind: App
metadata:
  name: my-app
spec:
  services:
    - name: webapp
      image: nginx
      port: 80
      ingress:
        host: localhost
  # cronjobs:
  #   - name: echos
  #     schedule: "* * * * *"
  #     image: alpine
  #     command: ["echo", "'hello'"]
  uses:
    - name: echo
      config:
        ping: pong-dong
