apiVersion: app.hostan.app/v1
kind: App
metadata:
  name: my-app
spec:
  services:
    - name: webapp
      image: nginx
      port: 80
      ingress:
        host: localhost
  uses:
    - name: echo
      config:
        ping: pong
